In [1]:
import numpy as np

In [2]:
from scipy import linalg

In [3]:
A=np.array([[0.995,0.690,0.000,0.000,0.000],[0.005,0.180,0.000,0.000,0.000],[0.000,0.020,0.310,0.500,0.000],[0.000,0.000,0.210,0.050,0.000],[0.000,0.050,0.000,0.000,0.585]])

In [4]:
print(A)

[[0.995 0.69  0.    0.    0.   ]
 [0.005 0.18  0.    0.    0.   ]
 [0.    0.02  0.31  0.5   0.   ]
 [0.    0.    0.21  0.05  0.   ]
 [0.    0.05  0.    0.    0.585]]


In [11]:
B=np.array([72.0,1.5,9.0,3.0,14.5])

In [12]:
B=B.T

In [13]:
print(B)

[72.   1.5  9.   3.  14.5]


In [14]:
X=linalg.solve(A,B)

In [15]:
print(X)

[67.89069172  6.44748079 11.80388247 10.42369364 24.23525805]
