In [3]:
import numpy as np

In [4]:
from scipy import linalg

In [5]:
A=np.array([[0.995,0.690,0.000,0.000,0.000],[0.005,0.180,0.000,0.000,0.000],[0.000,0.020,0.310,0.500,0.000],[0.000,0.000,0.210,0.050,0.000],[0.000,0.050,0.000,0.000,0.585]])

In [6]:
print(A)

[[0.995 0.69  0.    0.    0.   ]
 [0.005 0.18  0.    0.    0.   ]
 [0.    0.02  0.31  0.5   0.   ]
 [0.    0.    0.21  0.05  0.   ]
 [0.    0.05  0.    0.    0.585]]


In [7]:
B=np.array([72.0,1.5,9.0,3.0,14.5])

In [8]:
B=B.T

In [9]:
print(B)

[72.   1.5  9.   3.  14.5]


In [10]:
X=linalg.solve(A,B)

In [11]:
print(X)

[67.89069172  6.44748079 11.80388247 10.42369364 24.23525805]


In [20]:
A=np.array([[1,1],[1,0.5]])

In [21]:
print(A)

[[1.  1. ]
 [1.  0.5]]


In [22]:
B=np.array([[4,3.7]])

In [23]:
B=B.T

In [24]:
print(B)

[[4. ]
 [3.7]]


In [25]:
X=linalg.solve(A,B)

In [27]:
print(X)

[[3.4]
 [0.6]]
